### ISSUE TITLE
omitting some case class properties

### ISSUE THREAD

**Issue by behrad** [ReactiveCouchbase/ReactiveCouchbase-core#55]
Is there anyway I can keep a few of my case class properties from being persisted? they are transient :)
Is the only way writing my down JSON formatter?

**Comment by mathieuancelin** [comment]
Hi,

yes the only way to do that is to write your own Json Writer

**Comment by behrad** [comment]
Hi @mathieuancelin ,
default values did it!

```scala
case class ABC( name: Some[String] = None )
```

This worked :)
